version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: interface-server
    ports:
      - '80:80'

  db:
    image: mongo:latest
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: khaiadmin
      MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - ./data:/data/db
    networks:
      - db-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: khaiadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd
      ME_CONFIG_BASICAUTH_USERNAME: xodmf
      ME_CONFIG_BASICAUTH_PASSWORD: passwd
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
